### ISSUE TITLE
Rewriting to Python

### ISSUE THREAD

**Issue by masyagin1998** [bmstu-iu9/mill-db#4]
(Не туда, писал Саше Барлуке)

**Comment by Mazdaywik** [comment]
Не, Михаил. Задача по смыслу правильная и я её планирую предложить как курсовую по компиляторам. Сначала думал предложить как курсовую по БД, но в ней нет БД-шной специфики.

**Comment by masyagin1998** [comment]
Ура!

**Comment by Mazdaywik** [comment]
Задача выполнена!
